### ISSUE TITLE
Fix console Warnings around commercetools-frontend/permissions - single demanded permission

### ISSUE THREAD

**Issue by nspeet** [commercetools/commercetools-bundles-starter#120] opened 2021-07-29 17:55 UTC
Warning: @commercetools-frontend/permissions: It is recommended to pass a single demanded permission while using the hook, HoC or component multiple times.

**Comment by praveenkumarct** [comment] 2022-10-26 17:34
Check the details in the support ticket: https://github.com/commercetools/merchant-center-application-kit/issues/2438

- After upgrading to latest frontend libraries, we no more see many warnings(I still see 1 warning about this issue). But as explained [here](https://github.com/commercetools/merchant-center-application-kit/issues/2438#issuecomment-1081509349), this warning is from the navbar itself. 
- The root cause has been found, check [here](https://github.com/commercetools/merchant-center-application-kit/discussions/2731) for more details.

Hence closing this ticket.

**Closed by praveenkumarct** 2022-10-26 17:34 UTC
